# Generated by Django 2.0.6 on 2020-06-06 17:56

import ddos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_id', models.CharField(max_length=4)),
                ('resourse_ip', models.CharField(max_length=16)),
                ('attack_type', models.CharField(max_length=200)),
                ('attack_date', models.DateTimeField(verbose_name='date published')),
                ('attack_statistics', models.FileField(upload_to=ddos.models.user_directory_path)),
                ('attack_report', models.TextField(max_length=500)),
            ],
        ),
    ]
