# Generated by Django 2.0.6 on 2020-06-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='attack_id',
        ),
    ]
